apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: grafana-cloud-west
    name: grafana-cloud-west
    hash: dd6989ad37394aed2e73580bc1d37f31f333c4873918c7d0ebc071deea6a491c
    version: 1
    dateModified: 2023-10-15T12:20:55.258861-04:00
spec:
    type: grafana_cloud:1
    parameters:
        - name: metric_instance_id
          value: asdfasdf
        - name: api_key
          value: (sensitive)
          sensitive: true
        - name: gcp_zone
          value: prod-us-central-0
        - name: compression
          value: gzip
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
