apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: splunk-north
    name: splunk-north
    hash: edc9f468528b7f70a67b075e79cb48e17618b2361b91d7ffd19a54af71622a22
    version: 1
    dateModified: 2023-10-14T13:04:38.554209-04:00
spec:
    type: splunkhec:1
    parameters:
        - name: token
          value: asdfasdfasdfasdfasdf
        - name: index
          value: ""
        - name: hostname
          value: localhost
        - name: port
          value: 8088
        - name: path
          value: /services/collector/event
        - name: max_request_size
          value: 2.097152e+06
        - name: max_event_size
          value: 2.097152e+06
        - name: enable_compression
          value: true
        - name: enable_tls
          value: false
        - name: insecure_skip_verify
          value: false
        - name: ca_file
          value: ""
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
