apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: nr-otlp
spec:
    type: newrelic_otlp
    parameters:
        - name: endpoint
          value: https://otlp.nr-data.net
        - name: license_key
          value: (sensitive)
          sensitive: true
        - name: compression
          value: gzip
        - name: retry_on_failure_enabled
          value: false
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: false
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
---
apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    name: test
    labels:
        platform: linux
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - id: 01HCDADJGYVQ6CPKY6M3WHEASN
          type: otlp
          parameters:
            - name: listen_address
              value: 0.0.0.0
            - name: grpc_port
              value: 4391
            - name: http_port
              value: 4318
            - name: enable_tls
              value: false
            - name: cert_file
              value: ""
            - name: key_file
              value: ""
            - name: mutual_tls
              value: false
            - name: ca_file
              value: ""
            - name: enable_grpc_timeout
              value: true
            - name: grpc_max_connection_idle
              value: 60
            - name: grpc_max_connection_age
              value: 60
            - name: grpc_max_connection_age_grace
              value: 300
    destinations:
        - name: nr-otlp
    selector:
        matchLabels:
            configuration: test
