apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: 571de6d9-5670-48bd-9463-978a9ee92aff
    name: postgres-template
    description: Backend database (postgres) metrics and logs.
    labels:
        platform: linux
    hash: 90739ca9e158f007510d2c4fbf6c2f0a02a2a4f587692169562924638af6b54e
    version: 1
    dateModified: 2023-09-27T13:42:24.862679748Z
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - id: 01H4PJADWWSZZVFKPGC2NZJVB2
          type: postgresql:10
          parameters:
            - name: enable_metrics
              value: true
            - name: endpoint
              value: localhost:5432
            - name: transport
              value: tcp
            - name: username
              value: otel
            - name: password
              value: (sensitive)
              sensitive: true
            - name: databases
              value: []
            - name: collection_interval
              value: 60
            - name: enable_tls
              value: false
            - name: ca_file
              value: ""
            - name: cert_file
              value: ""
            - name: key_file
              value: ""
            - name: insecure_skip_verify
              value: false
            - name: disable_metrics
              value: []
            - name: enable_logs
              value: true
            - name: postgresql_log_path
              value:
                - /var/lib/pgsql/14/data/log/postgresql.log
            - name: start_at
              value: end
          processors:
            - id: 01H64AHDVB0ANN2M1EEEE3S99S
              type: filter_severity:4
              parameters:
                - name: severity
                  value: WARN
            - id: 01H7DNHN9RETA0FJ498DJRYM1W
              type: batch:3
              parameters:
                - name: send_batch_size
                  value: 200
                - name: send_batch_max_size
                  value: 400
                - name: timeout
                  value: 1s
    destinations:
        - id: 01H4PJADX2M2NKGR9SCHNHXDJG
          name: s3-archive:2
          processors:
            - id: 01H57R73PRRSENA41E6120TS9T
              type: batch:3
              parameters:
                - name: send_batch_size
                  value: 500
                - name: send_batch_max_size
                  value: 600
                - name: timeout
                  value: 2s
        - id: 01H4PJADX7JA3ZMXQT4835PZZA
          name: Splunk:8
          processors:
            - id: 01H4PJADQC8RR3049RF1XA4Q8Y
              displayName: Filter query log
              type: filter_field:6
              parameters:
                - name: telemetry_types
                  value:
                    - Logs
                - name: action
                  value: exclude
                - name: match_type
                  value: strict
                - name: resources
                  value: {}
                - name: attributes
                  value:
                    log_type: postgresql.slow_query
                - name: bodies
                  value: {}
    selector:
        matchLabels:
            configuration: postgres-template
status:
    latest: true
