apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: 2708798a-bffe-4058-99e8-c100af43ecef
    name: sales-endpoint-template
    description: Point of sale endpoint syslog and host metrics.
    labels:
        platform: linux
    hash: bf37dd5aaa66716aa3ef6706b5ce24ddc5d679e78b17a45af14d360d54bf8f9c
    version: 1
    dateModified: 2023-09-27T13:42:24.702664052Z
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - id: 01H57RC284YV4ZATJ63FMZNFKC
          type: host:3
          parameters:
            - name: metric_filtering
              value:
                - system.disk.io
                - system.disk.io_time
                - system.disk.merged
                - system.disk.operation_time
                - system.disk.operations
                - system.disk.pending_operations
                - system.disk.weighted_io_time
                - system.processes.count
                - system.processes.created
                - system.cpu.time
                - system.cpu.utilization
            - name: enable_process
              value: true
            - name: process_metrics_filtering
              value:
                - process.context_switches
                - process.cpu.utilization
                - process.disk.operations
                - process.memory.utilization
                - process.open_file_descriptors
                - process.paging.faults
                - process.signals_pending
                - process.threads
            - name: enable_process_filter
              value: false
            - name: process_include
              value: []
            - name: process_exclude
              value: []
            - name: process_filter_match_strategy
              value: regexp
            - name: collection_interval
              value: 60
          processors:
            - id: 01H57WXN1BCSPR86HN9BW36ND7
              type: batch:3
              parameters:
                - name: send_batch_size
                  value: 8192
                - name: send_batch_max_size
                  value: 0
                - name: timeout
                  value: 200ms
        - id: 01H57RC286BDB3YRVWPS68P2XZ
          type: syslog:2
          parameters:
            - name: listen_ip
              value: 0.0.0.0
            - name: listen_port
              value: 5140
            - name: protocol
              value: rfc3164
            - name: connection_type
              value: udp
            - name: data_flow
              value: high
            - name: timezone
              value: UTC
            - name: parse_to
              value: body
            - name: enable_octet_counting
              value: false
            - name: enable_non_transparent_framing_trailer
              value: false
            - name: non_transparent_framing_trailer
              value: LF
            - name: enable_mutual_tls
              value: false
            - name: cert_file
              value: ""
            - name: key_file
              value: ""
            - name: ca_file
              value: ""
            - name: tls_min_version
              value: "1.2"
          processors:
            - id: 01H57RG3FNMRQSB36XR7J2ZZ0J
              type: delete_fields:7
              parameters:
                - name: enable_logs
                  value: true
                - name: log_condition
                  value: "true"
                - name: log_resource_attributes
                  value:
                    - host.id
                - name: log_attributes
                  value: []
                - name: log_body_keys
                  value:
                    - proc_id
                - name: enable_metrics
                  value: false
                - name: datapoint_condition
                  value: "true"
                - name: metric_resource_attributes
                  value: []
                - name: metric_attributes
                  value: []
                - name: enable_traces
                  value: false
                - name: span_condition
                  value: "true"
                - name: trace_resource_attributes
                  value: []
                - name: trace_attributes
                  value: []
            - id: 01H57RG3FQ222Z0BC5TV4R0PNQ
              type: batch:3
              parameters:
                - name: send_batch_size
                  value: 200
                - name: send_batch_max_size
                  value: 200
                - name: timeout
                  value: 200ms
    destinations:
        - id: 01H57RC289G803SA426JC2R678
          name: Grafana:4
    selector:
        matchLabels:
            configuration: sales-endpoint-template
status:
    latest: true
