apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: workstation
    name: workstation
    labels:
        platform: linux
    hash: 334f90de533a6376f0940f5880e1878e26ae1f715a40d49812ad5c1d9a8df9e8
    version: 5
    dateModified: 2023-10-18T15:34:07.436716578Z
spec:
    contentType: ""
    measurementInterval: 1m
    sources:
        - id: 01HAMMMEZETEDTMET44TAT6A61
          type: host:3
          parameters:
            - name: metric_filtering
              value:
                - system.disk.io
                - system.disk.io_time
                - system.disk.merged
                - system.disk.operation_time
                - system.disk.operations
                - system.disk.pending_operations
                - system.disk.weighted_io_time
                - system.processes.count
                - system.processes.created
                - system.cpu.time
                - system.cpu.utilization
            - name: enable_process
              value: false
            - name: process_metrics_filtering
              value:
                - process.context_switches
                - process.cpu.time
                - process.cpu.utilization
                - process.disk.io
                - process.disk.operations
                - process.memory.usage
                - process.memory.utilization
                - process.memory.virtual
                - process.open_file_descriptors
                - process.paging.faults
                - process.signals_pending
                - process.threads
                - process.handles
            - name: enable_process_filter
              value: false
            - name: process_include
              value: []
            - name: process_exclude
              value: []
            - name: process_filter_match_strategy
              value: regexp
            - name: collection_interval
              value: 60
        - id: 01HAMMMEZH22JDSE415KN93C69
          type: file:9
          parameters:
            - name: file_path
              value:
                - /var/log/syslog
            - name: exclude_file_path
              value: []
            - name: log_type
              value: file
            - name: parse_format
              value: none
            - name: regex_pattern
              value: ""
            - name: multiline_parsing
              value: none
            - name: multiline_line_start_pattern
              value: ""
            - name: multiline_line_end_pattern
              value: ""
            - name: parse_timestamp
              value: false
            - name: timestamp_field
              value: timestamp
            - name: parse_timestamp_format
              value: RFC3339
            - name: epoch_timestamp_format
              value: s
            - name: manual_timestamp_format
              value: '%Y-%m-%dT%H:%M:%S.%f%z'
            - name: timezone
              value: UTC
            - name: parse_severity
              value: false
            - name: severity_field
              value: severity
            - name: include_file_name_attribute
              value: true
            - name: include_file_path_attribute
              value: false
            - name: include_file_name_resolved_attribute
              value: false
            - name: include_file_path_resolved_attribute
              value: false
            - name: encoding
              value: utf-8
            - name: poll_interval
              value: 200
            - name: max_concurrent_files
              value: 1024
            - name: parse_to
              value: body
            - name: start_at
              value: end
            - name: fingerprint_size
              value: 1kb
            - name: enable_offset_storage
              value: true
            - name: offset_storage_dir
              value: $OIQ_OTEL_COLLECTOR_HOME/storage
            - name: retry_on_failure_enabled
              value: false
            - name: retry_on_failure_initial_interval
              value: 1
            - name: retry_on_failure_max_interval
              value: 30
            - name: retry_on_failure_max_elapsed_time
              value: 300
            - name: enable_sorting
              value: false
            - name: sort_rules
              value: []
    destinations:
        - id: 01HAMMMEZPNTYFG1E17VTEK45D
          name: OTLP:2
          processors:
            - id: 01HAMMMP5KDBMHAMA40H2S8RNT
              type: batch:3
              parameters:
                - name: send_batch_size
                  value: 8192
                - name: send_batch_max_size
                  value: 0
                - name: timeout
                  value: 200ms
            - id: 01HD1PMJVMT248XHSPX037B9KK
              type: log_dedup:5
              parameters:
                - name: interval
                  value: 10
                - name: log_count_attribute
                  value: log_count
                - name: exclude_fields
                  value: []
                - name: timezone
                  value: UTC
    selector:
        matchLabels:
            configuration: workstation
status:
    rollout:
        name: ""
        status: 4
        options:
            startAutomatically: false
            rollbackOnFailure: true
            phaseAgentCount:
                initial: 3
                multiplier: 5
                maximum: 100
            maxErrors: 0
        phase: 13
        progress:
            completed: 1000
            errors: 0
            pending: 0
            waiting: 0
    currentVersion: 5
    pendingVersion: 5
    latest: true
    pending: true
    current: true
