receivers:
  hostmetrics:
    collection_interval: 1m
    scrapers:
      load:
      filesystem:
      memory:
      network:

processors:
  batch:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [logging]
