apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: 01H57Y7H0BHPW7VVF3JMH6QJAD
    name: Datadog
    hash: 9aeb494c28a45578a2d9b176129bfd3dce9c6e6461f1ba53bf4b39cde3ba9de9
    version: 2
    dateModified: 2023-09-20T17:16:07.496287987Z
spec:
    type: datadog:6
    parameters:
        - name: site
          value: US1
        - name: api_key
          value: (sensitive)
          sensitive: true
        - name: retry_on_failure_enabled
          value: false
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: false
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
