apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: Google
    name: Google
    hash: bfeb3c57273b968739c7a0e82a189918accd45ad47b144444e9ff5c7f77a1072
    version: 10
    dateModified: 2023-10-09T19:07:10.568303183Z
spec:
    type: googlecloud:12
    parameters:
        - name: project
          value: bindplane-op-demo
        - name: auth_type
          value: auto
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: ""
        - name: retry_on_failure_enabled
          value: false
        - name: retry_on_failure_initial_interval
          value: 3
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: false
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
        - name: enable_compression
          value: true
        - name: enable_wal
          value: false
        - name: wal_max_backoff
          value: 60
status:
    latest: true
