apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: Grafana
    name: Grafana
    hash: b9bf56c2e3eca8904df3594b88897474ed0bbc904e86ab09d1dd43ad8db07562
    version: 4
    dateModified: 2023-09-20T17:16:07.544238224Z
spec:
    type: grafana_cloud:5
    parameters:
        - name: metric_instance_id
          value: "0003339555"
        - name: api_key
          value: (sensitive)
          sensitive: true
        - name: gcp_zone
          value: prod-us-central-0
        - name: retry_on_failure_enabled
          value: false
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: false
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: false
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
