apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    id: New_Relic_Prod
    name: New_Relic_Prod
    hash: 629b04d555d136d60ba98b74020e97ab02f3ae21efd070e498e1e1379a37158a
    version: 2
    dateModified: 2023-09-20T17:16:07.551851226Z
spec:
    type: newrelic_otlp:5
    parameters:
        - name: endpoint
          value: https://otlp.nr-data.net
        - name: license_key
          value: (sensitive)
          sensitive: true
        - name: compression
          value: gzip
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
status:
    latest: true
