apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: 01HCZK16Z9QBWEP6XC7E1RC99Z
    name: my_otel_config
    hash: f1436bafa90fc1668d6877916d30ef5874f3dd84668380f549d82eee09dc1581
    version: 1
    dateModified: 2023-10-17T15:50:32.169361-04:00
spec:
    contentType: ""
    measurementInterval: ""
    raw: |-
        receivers:
          hostmetrics:
            collection_interval: 1m
            scrapers:
              load:
              filesystem:
              memory:
              network:

        processors:
          batch:

        exporters:
          logging:
            loglevel: debug

        service:
          pipelines:
            metrics:
              receivers: [hostmetrics]
              processors: [batch]
              exporters: [logging]
    selector:
        matchLabels:
            configuration: my_otel_config
status:
    latest: true
