apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: postgres-stage
    name: postgres-stage
    labels:
        platform: macos
    hash: 407bae770ea15222a1dc868d06ad3a34065936693db73bf4d11360f39935e7e7
    version: 1
    dateModified: 2023-10-14T13:02:54.611041-04:00
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - id: 01HCQJ8448HVANVPAGDASPGZ7T
          type: postgresql:1
          parameters:
            - name: enable_metrics
              value: true
            - name: endpoint
              value: localhost:5432
            - name: transport
              value: tcp
            - name: username
              value: asdfa
            - name: password
              value: (sensitive)
              sensitive: true
            - name: databases
              value: []
            - name: collection_interval
              value: 60
            - name: enable_tls
              value: false
            - name: ca_file
              value: ""
            - name: cert_file
              value: ""
            - name: key_file
              value: ""
            - name: insecure_skip_verify
              value: false
            - name: disable_metrics
              value: []
            - name: enable_logs
              value: true
            - name: postgresql_log_path
              value:
                - /var/log/postgresql/postgresql*.log
                - /var/lib/pgsql/data/log/postgresql*.log
                - /var/lib/pgsql/*/data/log/postgresql*.log
            - name: start_at
              value: end
        - id: 01HCQJ8448HVANVPAGDGSDWHVA
          type: host:1
          parameters:
            - name: metric_filtering
              value:
                - system.network.connections
                - system.network.conntrack.count
                - system.network.conntrack.max
                - system.network.dropped
                - system.network.errors
                - system.network.io
                - system.network.packets
                - system.memory.usage
                - system.memory.utilization
                - system.cpu.load_average.15m
                - system.cpu.load_average.1m
                - system.cpu.load_average.5m
                - system.disk.io
                - system.disk.io_time
                - system.disk.merged
                - system.disk.operation_time
                - system.disk.operations
                - system.disk.pending_operations
                - system.disk.weighted_io_time
                - system.processes.count
                - system.processes.created
                - system.cpu.time
                - system.cpu.utilization
            - name: enable_process
              value: true
            - name: process_metrics_filtering
              value:
                - process.context_switches
                - process.cpu.utilization
                - process.disk.operations
                - process.memory.utilization
                - process.open_file_descriptors
                - process.paging.faults
                - process.signals_pending
                - process.threads
                - process.handles
            - name: enable_process_filter
              value: false
            - name: process_include
              value: []
            - name: process_exclude
              value: []
            - name: process_filter_match_strategy
              value: regexp
            - name: collection_interval
              value: 60
    destinations:
        - id: 01HCQJ8448HVANVPAGDK34F680
          name: elastic-cluster-1:1
    selector:
        matchLabels:
            configuration: postgres-stage
status:
    latest: true
