apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    id: test
    name: test
    labels:
        platform: macos
    hash: 31f85616470b07379c70fdad96fd80981164fd1fd397ac64d35af3cb4c148dc5
    version: 4
    dateModified: 2023-10-15T18:15:19.72383-04:00
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - id: 01HCQH5V011SZTB6Q3G3JZGCPY
          type: macOS:1
          parameters:
            - name: enable_metrics
              value: true
            - name: collection_interval
              value: 60
            - name: enable_logs
              value: true
            - name: enable_system_log
              value: true
            - name: system_log_path
              value: /var/log/system.log
            - name: enable_install_log
              value: true
            - name: install_log_path
              value: /var/log/install.log
            - name: start_at
              value: end
        - id: 01HCQH5V011SZTB6Q3G5G691RD
          type: postgresql:1
          parameters:
            - name: enable_metrics
              value: false
            - name: endpoint
              value: localhost:5432
            - name: transport
              value: tcp
            - name: username
              value: ""
            - name: password
              value: (sensitive)
              sensitive: true
            - name: databases
              value: []
            - name: collection_interval
              value: 60
            - name: enable_tls
              value: false
            - name: ca_file
              value: ""
            - name: cert_file
              value: ""
            - name: key_file
              value: ""
            - name: insecure_skip_verify
              value: false
            - name: disable_metrics
              value: []
            - name: enable_logs
              value: true
            - name: postgresql_log_path
              value:
                - /var/log/postgresql/postgresql*.log
                - /var/lib/pgsql/data/log/postgresql*.log
                - /var/lib/pgsql/*/data/log/postgresql*.log
            - name: start_at
              value: end
        - id: 01HCT8ZS9BV1FT593TDV8SV5H4
          type: file:1
          parameters:
            - name: file_path
              value:
                - /Users/michaelkelly/fake-logs/apache.log
            - name: exclude_file_path
              value: []
            - name: log_type
              value: file
            - name: parse_format
              value: none
            - name: regex_pattern
              value: ""
            - name: multiline_parsing
              value: none
            - name: multiline_line_start_pattern
              value: ""
            - name: multiline_line_end_pattern
              value: ""
            - name: parse_timestamp
              value: false
            - name: timestamp_field
              value: timestamp
            - name: parse_timestamp_format
              value: RFC3339
            - name: epoch_timestamp_format
              value: s
            - name: manual_timestamp_format
              value: '%Y-%m-%dT%H:%M:%S.%f%z'
            - name: timezone
              value: UTC
            - name: parse_severity
              value: false
            - name: severity_field
              value: severity
            - name: include_file_name_attribute
              value: true
            - name: include_file_path_attribute
              value: false
            - name: include_file_name_resolved_attribute
              value: false
            - name: include_file_path_resolved_attribute
              value: false
            - name: encoding
              value: utf-8
            - name: poll_interval
              value: 200
            - name: max_concurrent_files
              value: 1024
            - name: parse_to
              value: body
            - name: start_at
              value: end
            - name: fingerprint_size
              value: 1kb
            - name: enable_offset_storage
              value: true
            - name: offset_storage_dir
              value: $OIQ_OTEL_COLLECTOR_HOME/storage
            - name: retry_on_failure_enabled
              value: false
            - name: retry_on_failure_initial_interval
              value: 1
            - name: retry_on_failure_max_interval
              value: 30
            - name: retry_on_failure_max_elapsed_time
              value: 300
            - name: enable_sorting
              value: false
            - name: sort_rules
              value: []
          processors:
            - id: 01HCT9VCR1BSCFKGNVE2G41BS5
              type: count_telemetry:1
              parameters:
                - name: enable_logs
                  value: false
                - name: log_match
                  value: "true"
                - name: log_metric_name
                  value: log.count
                - name: log_metric_units
                  value: '{logs}'
                - name: log_enable_attributes
                  value: false
                - name: enable_metrics
                  value: true
                - name: datapoint_match
                  value: "true"
                - name: datapoint_metric_name
                  value: datapoint.count
                - name: datapoint_metric_units
                  value: '{datapoints}'
                - name: datapoint_enable_attributes
                  value: false
                - name: enable_traces
                  value: false
                - name: span_match
                  value: "true"
                - name: span_metric_name
                  value: span.count
                - name: span_metric_units
                  value: '{spans}'
                - name: span_enable_attributes
                  value: false
                - name: interval
                  value: 60
    destinations:
        - id: 01HCQH5V011SZTB6Q3GBY9GVK2
          name: us-east1:1
        - id: 01HCQJCX3YRHCHDAM8CHNGDGMW
          name: splunk-north:1
    selector:
        matchLabels:
            configuration: test
status:
    currentVersion: 3
    pendingVersion: 3
    latest: true
