name: BindPlane OP Deploy and Export Raw
on:
  push:
    branches:
      - main
      - dev

jobs:
  bindplane:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: mkdir download

      - name: Install BindPlane CLI
        run: |
          curl -o bindplane.zip https://storage.googleapis.com/bindplane-op-releases/bindplane/bindplane-ee-v1.30.0-linux-amd64.zip
          unzip bindplane.zip
          sudo chmod +x bindplane
          sudo mv bindplane /usr/local/bin/bindplane
        working-directory: download

      - name: Create Profile
        run: |
          bindplane profile set gitflow \
            --remote-url https://app.bindplane.com \
            --api-key ${{ secrets.BINDPLANE_API_KEY }}
          bindplane profile use gitflow

      - name: Test CLI
        run: bindplane version

      - name: Deploy Resources
        run: bash ./gitops_workflow_standard/apply_bindplane_configs.sh

      - name: Export and checkin otel
        run: bash ./gitops_workflow_standard/get_bindplane_otel_configs.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Automated changes"
          git push
